name: candidate
recipe: drupal9
config:
  webroot: ./web
  php: '8.0'
  composer_version: '2.0.7'
  via: apache:2.4
  database: mysql:5.7
  drush: false

services:
  phpmyadmin:
    type: phpmyadmin
  appserver:
    build:
      - composer install;
      - mkdir -p /app/web/sites/default/files/tmp;

tooling:
